# Setup
title: Longkang Peng
description: Ph.D. Candidate<br>Department of Land Surveying and Geo-Informatics, The Hong Kong Polytechnic University
url: https://lk-peng.github.io/
avatar: /me.jpg
paginate: 5
permalink: pretty
cover_image: /bg3.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
  # - _posts  # do not show the post

# Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
# logo: logo.png
# social:
#   name: Longkang Peng
#   links:
    # - https://twitter.com/vszhub
    # - https://github.com/LK-Peng
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
# author:
#   name: Longkang Peng
#   url: https://github.com/LK-Peng
#   email: longkang.peng@connect.polyu.hk

<a href="https://info.flagcounter.com/7B8v"><img src="https://s01.flagcounter.com/map/7B8v/size_l/txt_000000/border_CCCCCC/pageviews_1/viewers_0/flags_0/" alt="Flag Counter" border="0"></a>

<script type="text/javascript" id="clstr_globe" src="//clustrmaps.com/globe.js?d=ZiymA_uq4-VnvAzCIW8XxGf9VYYUYe0AIUnxJiH_ZGw"></script>
